# url: alejandro.giacometti.me
name: AG
markdown: kramdown
safe: true
sass:
  sass_dir: assets/_sass
  style: :compressed
exclude: [Gemfile, Gemfile.lock, README.md, bower.json, cache.manifest, ]
highlighter: pygments
relative_permalinks: true
permalink: /:month-:day-:year/:title/
author: "Alejandro Giacometti"
location: "London, UK"

defaults:
  -
    scope:
      path: "" # empty string for all files
      type: "posts"
    values:
      layout: "blog"
      lang: en
  -
    scope:
      path: "page/"
      type: "pages"
    values:
      layout: "page" # overrides previous default layout

# prose.io
prose:
  rooturl: '_posts'
  siteurl: 'http://janrito.github.io'
  # relativeLinks: 'http://janrito.github.io/api/links.jsonp'
  media: 'images'
  ignore:
    - index.md
    - archivo.md
    - _config.yml
    - /_layouts
    - /_includes
    - /_data
    - /assets/
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          options: 'http://janrito.github.io/api/tags.jsonp'
          alterable: true
      - name: "date"
          field:
            element: "text"
            label: "Date (YYYY-MM-DD HH:MM:SS)"
            value: "2014-06-08 10:30:00"
    _posts/page:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "type"
        field:
          element: "hidden"
          value: "pages"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""