name: AG
markdown: kramdown
sass:
  sass_dir: assets/_sass
  style: :compressed
paginate: 15
highlighter: pygments
relative_permalinks: true
permalink: /:month-:day-:year/:title/
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "blog"
      author: Alejandro Giacometti
      lang: en
  -
    scope:
      path: "page/"
    values:
      layout: "page" # overrides previous default layout

