baseurl: "http://alejandro.giacometti.me"
name: AG
markdown: kramdown
sass:
  sass_dir: assets/_sass
  style: :compressed
gems:
- jekyll-mentions
# - jekyll-redirect-from
- jekyll-sitemap
exclude: [Gemfile, Gemfile.lock, README.md, bower.json, cache.manifest, ]
highlighter: pygments
timezone: "Europe/London"
permalink: /:year-:month-:day/:title/
n_recent_posts: 8
author: "Alejandro Giacometti"
location: "London, UK"
description: >
  This is the personal site of Alejandro Giacometti,
  a Digital Humanities researcher, currently lives in London.
meta_image: "/images/portrait.jpeg"

defaults:
  -
    scope:
      path: "" # empty string for all files
      type: "posts"
    values:
      layout: "blog"
      lang: en
      author: "Alejandro Giacometti"
      meta_type: "article"
  -
    scope:
      path: "page/"
      type: "pages"
    values:
      layout: "page" # overrides previous default layout
      meta_type: "website"

# prose.io
prose:
  rooturl: '_posts'
  siteurl: 'http://alejandro.giacometti.me'
  # relativeLinks: 'http://janrito.github.io/api/links.jsonp'
  media: 'images'
  ignore:
    - index.md
    - archivo.md
    - _config.yml
    - /_layouts
    - /_includes
    - /_data
    - /assets/
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          options: 'http://alejandro.giacometti.me/api/tags.jsonp'
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date (YYYY-MM-DD HH:MM:SS)"
          value: "2014-06-08 10:30:00"
    _posts/page:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "type"
        field:
          element: "hidden"
          value: "pages"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
