# url: alejandro.giacometti.me
name: AG
markdown: kramdown
safe: true
sass:
  sass_dir: assets/_sass
  style: :compressed
exclude: [Gemfile, Gemfile.lock, README.md, bower.json, cache.manifest, ]
highlighter: pygments
relative_permalinks: true
permalink: /:month-:day-:year/:title/
author: "Alejandro Giacometti"
location: "London, UK"

defaults:
  -
    scope:
      path: "" # empty string for all files
      type: "posts"
    values:
      layout: "blog"
      lang: en
  -
    scope:
      path: "page/"
      type: "pages"
    values:
      layout: "page" # overrides previous default layout

