baseurl: "http://alejandro.giacometti.me"
name: AG
markdown: kramdown
sass:
  sass_dir: assets/_sass
  style: :compressed
gems:
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
exclude: [Gemfile, Gemfile.lock, README.md, bower.json, cache.manifest, ]
highlighter: rouge
timezone: "Europe/London"
permalink: /:year-:month-:day/:title/
n_recent_posts: 4
author: "Alejandro Giacometti"
location: "London, UK"
description: >
  This is the personal site of Alejandro Giacometti,
  a Digital Humanities researcher, currently lives in London.
meta_image: "/images/portrait.jpeg"

defaults:
  -
    scope:
      path: ""
    values:
      lang: en
      meta_type: "website"
      author: "Alejandro Giacometti"
      js_main: 'main'
  -
    scope:
      path: "" # empty string for all files
      type: "posts"
    values:
      layout: "blog"
      meta_type: "article"
  -
    scope:
      path: "page/"
    values:
      layout: "page" # overrides previous default layout
      meta_type: "website"
  - scope:
      path: "assets/"
    values:
      sitemap: false